PERI_Project/Controllers/Owner/otherSpendingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PERI_Project.Models;

namespace PERI_Project.Controllers.Owner
{
    public class otherSpendingController : Controller
    {
        private PERIEntityDB db = new PERIEntityDB();

        // GET: otherSpending
        public ActionResult Index()
        {
            return View(db.tbl_otherSpending.ToList());
        }

        // GET: otherSpending/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_otherSpending tbl_otherSpending = db.tbl_otherSpending.Find(id);
            if (tbl_otherSpending == null)
            {
                return HttpNotFound();
            }
            return View(tbl_otherSpending);
        }

        // GET: otherSpending/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: otherSpending/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pk_id_otherSpending,name,spending_value,date")] tbl_otherSpending tbl_otherSpending)
        {
            if (ModelState.IsValid)
            {
                tbl_otherSpending.date = DateTime.Now;
                db.tbl_otherSpending.Add(tbl_otherSpending);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_otherSpending);
        }

        // GET: otherSpending/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_otherSpending tbl_otherSpending = db.tbl_otherSpending.Find(id);
            if (tbl_otherSpending == null)
            {
                return HttpNotFound();
            }
            return View(tbl_otherSpending);
        }

        // POST: otherSpending/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "pk_id_otherSpending,name,spending_value,date")] tbl_otherSpending tbl_otherSpending)
        {
            if (ModelState.IsValid)
            {
                tbl_otherSpending.date = DateTime.Now;
                db.Entry(tbl_otherSpending).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_otherSpending);
        }

        // GET: otherSpending/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_otherSpending tbl_otherSpending = db.tbl_otherSpending.Find(id);
            if (tbl_otherSpending == null)
            {
                return HttpNotFound();
            }
            return View(tbl_otherSpending);
        }

        // POST: otherSpending/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_otherSpending tbl_otherSpending = db.tbl_otherSpending.Find(id);
            db.tbl_otherSpending.Remove(tbl_otherSpending);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PERI_Project/Views/otherSpending/Create.cshtml
@model PERI_Project.Models.tbl_otherSpending

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">
            <h4>Create Other Spending</h4>
            <hr />
            <div class="form-group">
                <label class="text">Information : <label> Form is required (</label><label style="color:red"> * </label>)</label>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <label class="control-label col-md-2"><b>Name<label style="color:red"> *</label></b></label>
                @*@Html.LabelFor(model => model.name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2"><b>Spending<label style="color:red"> *</label></b></label>
                @*@Html.LabelFor(model => model.spending_value, "Spending", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.spending_value, new { htmlAttributes = new { @class = "form-control", @onkeyup = "validAngka(this)", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.spending_value, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                    @Html.LabelFor(model => model.date,"Date", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "otherSpending")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts_UserLogin/ScriptValidationAngka.js"></script>

PERI_Project/Views/otherSpending/Delete.cshtml
@model PERI_Project.Models.tbl_otherSpending

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3 class="text-success">Are you sure you want to delete this?</h3>
    <div>
        <h4>Delete Other Spending</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Name
                @*@Html.DisplayNameFor(model => model.name)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.name)
            </dd>

            <dt>
                Spending
                @*@Html.DisplayNameFor(model => model.spending_value)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.spending_value)
            </dd>

            <dt>
                Date
                @*@Html.DisplayNameFor(model => model.date)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>

        </dl>


    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-info" href="@Url.Action("Index", "otherSpending")">Back to List</a>
        </div>
    </div>
}

PERI_Project/Views/otherSpending/Details.cshtml
@model PERI_Project.Models.tbl_otherSpending

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Details Other Spending</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.spending_value)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.spending_value)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.date)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.date)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.pk_id_otherSpending }) |
    @Html.ActionLink("Back to List", "Index")
</p>

PERI_Project/Views/otherSpending/Edit.cshtml
@model PERI_Project.Models.tbl_otherSpending

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="container">
    <div class="form-horizontal">
        <h4>Edit Other Spending</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.pk_id_otherSpending)

        <div class="form-group">
            @Html.LabelFor(model => model.name,"Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control", @required = "required" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.spending_value,"Spending", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.spending_value, new { htmlAttributes = new { @class = "form-control" , @onkeyup = "validAngka(this)", @required = "required" } })
                @Html.ValidationMessageFor(model => model.spending_value, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.date,"Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-secondary" /> |
                <a class="btn btn-info" href="@Url.Action("Index", "otherSpending")">Back to List</a>
            </div>
        </div>
    </div>
</div>
}
<script src="~/Scripts_UserLogin/ScriptValidationAngka.js"></script>

PERI_Project/Views/otherSpending/Index.cshtml
@model IEnumerable<PERI_Project.Models.tbl_otherSpending>

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.spending_value)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.spending_value)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.pk_id_otherSpending }) |
            @Html.ActionLink("Details", "Details", new { id=item.pk_id_otherSpending }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.pk_id_otherSpending })
        </td>
    </tr>
}

</table>*@

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h3 class="m-0 font-weight-bold text-success">Data Other Spending</h3>
        </div>
        <div class="card-header py-3">
            <a class="btn btn-success" href="@Url.Action("Create","otherSpending")">Add Other Spending</a>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="DataTableNoSort" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No. Other Spending</th>
                            <th>Other Spending Name</th>
                            <th>Spending</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No. Other Spending</th>
                            <th>Other Spending Name</th>
                            <th>Spending</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.pk_id_otherSpending)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.spending_value)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.date)
                                </td>
                                <td>
                                    <a class="btn btn-primary" href="@Url.Action("Edit", "otherSpending" , new { id = item.pk_id_otherSpending } )"><img src="~/images/edit.png" /> Edit</a> |
                                    @*<a class="btn btn-secondary" href="@Url.Action("Details", "otherIncome" , new { id = item.pk_id_otherIncome } )"><img src="~/images/details.png" /> Details</a> |*@
                                    <a class="btn btn-danger" href="@Url.Action("Delete", "otherSpending" , new { id = item.pk_id_otherSpending } )"><img src="~/images/bin.png" /> Delete</a>
                                    @*@Html.ActionLink("Edit", "Edit", new { id = item.pk_id_otherSpending }) |
                                    @Html.ActionLink("Details", "Details", new { id = item.pk_id_otherSpending }) |
                                    @Html.ActionLink("Delete", "Delete", new { id = item.pk_id_otherSpending })*@
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>