PERI_Project/Controllers/Admin/OrderRequestController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PERI_Project.Models;

namespace PERI_Project.Controllers.Admin
{
    public class OrderRequestController : Controller
    {
        private PERIEntityDB db = new PERIEntityDB();

        // GET: OrderRequest
        public ActionResult Index()
        {
            var request = db.tbl_OrderRequest.Where(item => item.status == "Not Yet").OrderByDescending(item => item.pk_id_OrderRequest);
            return View(request.ToList());
        }
        public ActionResult IndexDone()
        {
            var request = db.tbl_OrderRequest.Where(item=>item.status=="Done").OrderByDescending(item => item.pk_id_OrderRequest);
            return View(request.ToList());
        }
        // GET: OrderRequest/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_OrderRequest tbl_OrderRequest = db.tbl_OrderRequest.Find(id);
            if (tbl_OrderRequest == null)
            {
                return HttpNotFound();
            }
            return View(tbl_OrderRequest);
        }

        // GET: OrderRequest/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrderRequest/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pk_id_OrderRequest,Name,address,phone,email,description,status")] tbl_OrderRequest tbl_OrderRequest)
        {
            if (ModelState.IsValid)
            {
                db.tbl_OrderRequest.Add(tbl_OrderRequest);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tbl_OrderRequest);
        }

        // GET: OrderRequest/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_OrderRequest tbl_OrderRequest = db.tbl_OrderRequest.Find(id);
            Session["Request"] = tbl_OrderRequest;
            tbl_customerOrder customerOrder = new tbl_customerOrder();
            customerOrder.name = tbl_OrderRequest.Name;
            customerOrder.phone = tbl_OrderRequest.phone;
            customerOrder.email = tbl_OrderRequest.email;
            db.tbl_customerOrder.Add(customerOrder);
            tbl_OrderRequest.status = "Done";
            db.Entry(tbl_OrderRequest).State = EntityState.Modified;
            db.SaveChanges();
            Session["Customer"] = customerOrder;
            if (tbl_OrderRequest == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Create", "order");
        }
        
        // POST: OrderRequest/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "pk_id_OrderRequest,Name,address,phone,email,description,status")] tbl_OrderRequest tbl_OrderRequest)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_OrderRequest).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tbl_OrderRequest);
        }

        // GET: OrderRequest/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_OrderRequest tbl_OrderRequest = db.tbl_OrderRequest.Find(id);
            if (tbl_OrderRequest == null)
            {
                return HttpNotFound();
            }
            return View(tbl_OrderRequest);
        }

        // POST: OrderRequest/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_OrderRequest tbl_OrderRequest = db.tbl_OrderRequest.Find(id);
            db.tbl_OrderRequest.Remove(tbl_OrderRequest);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Done(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_OrderRequest tbl_OrderRequest = db.tbl_OrderRequest.Find(id);
            tbl_OrderRequest.status = "Done";
            db.Entry(tbl_OrderRequest).State = EntityState.Modified;
            db.SaveChanges();
            if (tbl_OrderRequest == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index");
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PERI_Project/Views/OrderRequest/Create.cshtml
@model PERI_Project.Models.tbl_OrderRequest

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>tbl_OrderRequest</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

PERI_Project/Views/OrderRequest/Delete.cshtml
@model PERI_Project.Models.tbl_OrderRequest

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>tbl_OrderRequest</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>

            <dt>
                Address
                @*@Html.DisplayNameFor(model => model.address)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.address)
            </dd>

            <dt>
                Phone
                @*@Html.DisplayNameFor(model => model.phone)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.phone)
            </dd>

            <dt>
                Email
                @*@Html.DisplayNameFor(model => model.email)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.email)
            </dd>

            <dt>
                Description
                @*@Html.DisplayNameFor(model => model.description)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.description)
            </dd>

            <dt>
                Status
                @*@Html.DisplayNameFor(model => model.status)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.status)
            </dd>

        </dl>


    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-info" href="@Url.Action("Index", "OrderRequest")">Back to List</a>
        </div>
    </div>
}

PERI_Project/Views/OrderRequest/Details.cshtml
@model PERI_Project.Models.tbl_OrderRequest

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h4>Order Request Details</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.status)
        </dd>

    </dl>
    <p>
        @*<a class="btn btn-primary" href="@Url.Action("Edit", "OrderRequest" , new { id = Model.pk_id_OrderRequest } )"><img src="~/images/edit.png" /> Edit</a> |*@
        @*@Html.ActionLink("Edit", "Edit", new { id = Model.pk_id_OrderRequest }) |*@
        <a class="btn btn-info" href="@Url.Action("Index", "OrderRequest")">Back to List</a>
        @*@Html.ActionLink("Back to List", "Index", "payment", new { }, new { })*@

    </p>
</div>

PERI_Project/Views/OrderRequest/Edit.cshtml
@model PERI_Project.Models.tbl_OrderRequest

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="container">
        <div class="form-horizontal">
            <h4>Order Request</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.pk_id_OrderRequest)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, "Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.address,"Address", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.phone,"Phone", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.phone, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.phone, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.email,"Email", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.description,"Description", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.status,"Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-secondary" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "OrderRequest")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}

PERI_Project/Views/OrderRequest/Index.cshtml
@model IEnumerable<PERI_Project.Models.tbl_OrderRequest>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.pk_id_OrderRequest }) |
            @Html.ActionLink("Details", "Details", new { id=item.pk_id_OrderRequest }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.pk_id_OrderRequest })
        </td>
    </tr>
}*@

@*</table>*@
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-success">Data Order Request</h3>
    </div>
    @*<div class="card-header py-3">
        <a class="btn btn-success" href="@Url.Action("IndexDone","OrderRequest")">Done</a>
    </div>*@
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="DataTableNoSort" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No. Request</th>
                        <th>Customer Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>No. Request</th>
                        <th>Customer Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Date</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.pk_id_OrderRequest)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.phone)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.status)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.date)
                        </td>

                        <td>
                            <a class="btn btn-primary" href="@Url.Action("Edit", "OrderRequest" , new { id = item.pk_id_OrderRequest } )">@*<img src="~/images/edit.png" />*@ Process</a> <hr />
                            <a class="btn btn-secondary" href="@Url.Action("Details", "OrderRequest" , new { id = item.pk_id_OrderRequest } )"><img src="~/images/details.png" /> Details</a> <hr />
                            @*<a class="btn btn-success" href="@Url.Action("Done", "OrderRequest" , new { id = item.pk_id_OrderRequest } )"><img src="~/images/edit.png" /> Done</a>*@
                            <a class="btn btn-danger" href="@Url.Action("Delete", "OrderRequest" , new { id = item.pk_id_OrderRequest } )"><img src="~/images/bin.png" /> Delete</a>
                        </td>
                    </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

PERI_Project/Views/OrderRequest/IndexDone.cshtml
@model IEnumerable<PERI_Project.Models.tbl_OrderRequest>

@{
    ViewBag.Title = "IndexDone";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h3 class="m-0 font-weight-bold text-success">Data Order Request</h3>
    </div>
    @*<div class="card-header py-3">
        <a class="btn btn-success" href="@Url.Action("Index","OrderRequest")">Not Yet</a>
    </div>*@
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="DataTableNoSort" width="100%" cellspacing="0">
                <thead>
                    <tr>
                        <th>No. Request</th>
                        <th>Customer Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th>No. Request</th>
                        <th>Customer Name</th>
                        <th>Phone</th>
                        <th>Email</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.pk_id_OrderRequest)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.phone)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.email)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.status)
                            </td>

                            <td>
                                @*<a class="btn btn-primary" href="@Url.Action("Edit", "OrderRequest" , new { id = item.pk_id_OrderRequest } )"><img src="~/images/edit.png" /> Edit</a> |*@
                                <a class="btn btn-secondary" href="@Url.Action("Details", "OrderRequest" , new { id = item.pk_id_OrderRequest } )"><img src="~/images/details.png" /> Details</a>
                                @*<a class="btn btn-primary" href="@Url.Action("Done", "OrderRequest" , new { id = item.pk_id_OrderRequest } )"><img src="~/images/edit.png" /> Done</a> |*@

                                @*<a class="btn btn-danger" href="@Url.Action("Delete", "payment" , new { id = item.pk_id_payment } )"><img src="~/images/bin.png" /> Delete</a>*@
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>