PERI_Project/Controllers/Owner/Owner_debtController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PERI_Project.Models;

namespace PERI_Project.Controllers.Owner
{
    public class Owner_debtController : Controller
    {
        private PERIEntityDB db = new PERIEntityDB();

        // GET: Owner_debt
        public ActionResult Index()
        {
            var tbl_Owner_debt = db.tbl_Owner_debt.Include(t => t.tbl_spending).OrderByDescending(item => item.pk_id_oDebt);
            return View(tbl_Owner_debt.ToList());
        }

        // GET: Owner_debt/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Owner_debt tbl_Owner_debt = db.tbl_Owner_debt.Find(id);
            if (tbl_Owner_debt == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index","HistoryOwnerDebt",new { id = id });
        }

        // GET: Owner_debt/Create
        public ActionResult Create()
        {
            ViewBag.fk_id_spending = new SelectList(db.tbl_spending, "pk_id_spending", "payment_status");
            return View();
        }

        // POST: Owner_debt/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "pk_id_oDebt,fk_id_spending,debt_status,date,payment,debt")] tbl_Owner_debt tbl_Owner_debt)
        {
            if (ModelState.IsValid)
            {
                db.tbl_Owner_debt.Add(tbl_Owner_debt);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.fk_id_spending = new SelectList(db.tbl_spending, "pk_id_spending", "payment_status", tbl_Owner_debt.fk_id_spending);
            return View(tbl_Owner_debt);
        }

        // GET: Owner_debt/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Owner_debt tbl_Owner_debt = db.tbl_Owner_debt.Find(id);
            if (tbl_Owner_debt == null)
            {
                return HttpNotFound();
            }
            ViewBag.fk_id_spending = new SelectList(db.tbl_spending, "pk_id_spending", "payment_status", tbl_Owner_debt.fk_id_spending);
            return View(tbl_Owner_debt);
        }

        // POST: Owner_debt/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "pk_id_oDebt,fk_id_spending,debt_status,date,payment,debt")] tbl_Owner_debt tbl_Owner_debt)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tbl_Owner_debt).State = EntityState.Modified;
                tbl_Owner_debt.date = DateTime.Now;
                tbl_spending spending = db.tbl_spending.Find(tbl_Owner_debt.fk_id_spending);
                spending.payment += tbl_Owner_debt.payment;
                if (spending.payment > spending.tbl_spendingItem.price) 
                {
                    tbl_depositSpending deposit = new tbl_depositSpending();
                    deposit.fk_id_spending = spending.pk_id_spending;
                    deposit.deposit = spending.payment - spending.tbl_spendingItem.price;
                    deposit.date = DateTime.Now;
                    //deposit.date = tbl_Owner_debt.date;
                    db.tbl_depositSpending.Add(deposit);
                    spending.payment_status = "Deposit";
                    //spending.payment = spending.tbl_spendingItem.price;
                }
               else if (spending.payment == spending.tbl_spendingItem.price)
                {
                    tbl_Owner_debt.debt_status = "Done";
                    spending.payment_status = "Done";
                }
                tbl_Owner_debt.debt -= tbl_Owner_debt.payment;
                if (tbl_Owner_debt.debt < 0) 
                {
                    tbl_Owner_debt.debt = 0;
                }
                tbl_HistoryOwnerDebt HistoryDebt = new tbl_HistoryOwnerDebt();
                HistoryDebt.fk_id_OwnerDebt = tbl_Owner_debt.pk_id_oDebt;
                HistoryDebt.payment = tbl_Owner_debt.payment;
                HistoryDebt.date = DateTime.Now;
                //HistoryDebt.date = tbl_Owner_debt.date;
                db.tbl_HistoryOwnerDebt.Add(HistoryDebt);
                tbl_Owner_debt.payment = null;
                db.Entry(tbl_Owner_debt).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.fk_id_spending = new SelectList(db.tbl_spending, "pk_id_spending", "payment_status", tbl_Owner_debt.fk_id_spending);
            return View(tbl_Owner_debt);
        }

        // GET: Owner_debt/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_Owner_debt tbl_Owner_debt = db.tbl_Owner_debt.Find(id);
            if (tbl_Owner_debt == null)
            {
                return HttpNotFound();
            }
            return View(tbl_Owner_debt);
        }

        // POST: Owner_debt/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            tbl_Owner_debt tbl_Owner_debt = db.tbl_Owner_debt.Find(id);
            db.tbl_Owner_debt.Remove(tbl_Owner_debt);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PERI_Project/Views/Owner_debt/Create.cshtml
@model PERI_Project.Models.tbl_Owner_debt

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">
            <h4>Create Owner Debt</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.fk_id_spending, "fk_id_spending", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("fk_id_spending", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.fk_id_spending, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.debt_status, "Debt Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.debt_status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.debt_status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.payment,"Paymnet", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.payment, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.payment, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.debt,"Debt", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.debt, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.debt, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.date,"Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "Owner_debt")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}

PERI_Project/Views/Owner_debt/Delete.cshtml
@model PERI_Project.Models.tbl_Owner_debt

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3 class="text-success">Are you sure you want to delete this?</h3>
    <div>
        <h4>Delete Owner Debt</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Debt Status
                @*@Html.DisplayNameFor(model => model.debt_status)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.debt_status)
            </dd>

            <dt>
                Payment
                @*@Html.DisplayNameFor(model => model.payment)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.payment)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.debt)
            </dt>

            <dd>
                Debt
                @*@Html.DisplayFor(model => model.debt)*@
            </dd>

            <dt>
                Payment Status
                @*@Html.DisplayNameFor(model => model.tbl_spending.payment_status)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_spending.payment_status)
            </dd>

            <dt>
                Date
                @*@Html.DisplayNameFor(model => model.date)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>

        </dl>


    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-info" href="@Url.Action("Index", "Owner_debt")">Back to List</a>
            @*@Html.ActionLink("Back to List", "Index")*@
        </div>
    </div>
}

PERI_Project/Views/Owner_debt/Details.cshtml
@model PERI_Project.Models.tbl_Owner_debt

@{
    
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container">
        <h4>Details Owner Debt</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                Debt Status
                @*@Html.DisplayNameFor(model => model.debt_status)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.debt_status)
            </dd>

            <dt>
                Payment
                @*@Html.DisplayNameFor(model => model.payment)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.payment)
            </dd>

            <dt>
                Debt
                @*@Html.DisplayNameFor(model => model.debt)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.debt)
            </dd>

            <dt>
                Payment Status
                @*@Html.DisplayNameFor(model => model.tbl_spending.payment_status)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_spending.payment_status)
            </dd>

            <dt>
                Date
                @*@Html.DisplayNameFor(model => model.date)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>

        </dl>
        <p>
            <a class="btn btn-primary" href="@Url.Action("Edit", "Owner_debt" , new { id = Model.pk_id_oDebt } )"><img src="~/images/edit.png" /> Pay</a> |
            <a class="btn btn-info" href="@Url.Action("Index", "Owner_debt")">Back to List</a>
            @*@Html.ActionLink("Edit", "Edit", new { id = Model.pk_id_oDebt }) |
            @Html.ActionLink("Back to List", "Index")*@
        </p>
    </div>

PERI_Project/Views/Owner_debt/Edit.cshtml
@model PERI_Project.Models.tbl_Owner_debt

@{
    if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">
            <h4>Payment Owner Debt</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.pk_id_oDebt)
            @Html.HiddenFor(model => model.fk_id_spending)

            @*<div class="form-group">
            @Html.LabelFor(model => model.fk_id_spending, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fk_id_spending, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.fk_id_spending, "", new { @class = "text-danger" })
            </div>
        </div>*@
            <div class="form-group">
                @Html.LabelFor(model => model.debt_status, "Debt Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.debt_status, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.debt_status, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.debt, "Debt", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.debt, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.debt, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.payment, "Payment", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.payment, new { htmlAttributes = new { @class = "form-control", @required = "required" ,@onkeyup = "validAngka(this)" } })
                    @Html.ValidationMessageFor(model => model.payment, "", new { @class = "text-danger" })
                </div>
            </div>



            @*<div class="form-group">
            @Html.LabelFor(model => model.date,"Date", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-secondary" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "Owner_debt")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}
<script src="~/Scripts_UserLogin/ScriptValidationAngka.js"></script>

PERI_Project/Views/Owner_debt/Index.cshtml
@model IEnumerable<PERI_Project.Models.tbl_Owner_debt>

@{
     if (Convert.ToInt16(Session["UserRoleID"]) != 2)
    {
        Response.Redirect("~/AdminLogin/Login");
    }
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.debt_status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.date)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.payment)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.debt)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.tbl_spending.payment_status)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.debt_status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.date)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.payment)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.debt)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.tbl_spending.payment_status)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.pk_id_oDebt }) |
            @Html.ActionLink("Details", "Details", new { id=item.pk_id_oDebt }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.pk_id_oDebt })
        </td>
    </tr>
}

</table>*@

    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h3 class="m-0 font-weight-bold text-success">Data Owner Debt</h3>
        </div>
        @*<div class="card-header py-3">
            <a class="btn btn-success" href="@Url.Action("Create","design")">Add Design</a>
        </div>*@
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="DataTableNoSort" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>No. Spending</th>
                            <th>Spending Name</th>
                            <th>Debt Status</th>
                            <th>Debt</th>
                            <th>Payment</th>
                            <th>Payment Status</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>No. Spending</th>
                            <th>Spending Name</th>
                            <th>Debt Status</th>
                            <th>Debt</th>
                            <th>Payment</th>
                            <th>Payment Status</th>
                            <th>Date</th>
                            <th>Action</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        @foreach (var item in Model)
                        {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.fk_id_spending)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_spending.tbl_spendingItem.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.debt_status)
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.debt)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.payment)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.tbl_spending.payment_status)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.date)
                            </td>
                            <td>
                                @if (item.debt_status == "Done") {

                                }
                                else {
                                    <a class="btn btn-primary" href="@Url.Action("Edit", "Owner_debt" , new { id = item.pk_id_oDebt } )"><img src="~/images/edit.png" /> Pay</a> <hr />
                                }
                                <a class="btn btn-secondary" href="@Url.Action("Details", "Owner_debt" , new { id = item.pk_id_oDebt } )"><img src="~/images/details.png" /> History</a>
                                @*<a class="btn btn-danger" href="@Url.Action("Delete", "Owner_debt" , new { id = item.pk_id_oDebt } )"><img src="~/images/bin.png" /> Delete</a>*@
                                @*@Html.ActionLink("Edit", "Edit", new { id = item.pk_id_oDebt }) |
        @Html.ActionLink("Details", "Details", new { id = item.pk_id_oDebt }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.pk_id_oDebt })*@
                            </td>
                        </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>