PERI_Project/Controllers/Admin/orderController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.IO;
using PERI_Project.Models;

namespace PERI_Project.Controllers.Admin
{
    public class orderController : Controller
    {
        private PERIEntityDB db = new PERIEntityDB();

        // GET: order
        public ActionResult Index()
        {
            var tbl_order = db.tbl_order.Include(t => t.tbl_customerOrder).Include(t => t.tbl_design).Include(t => t.tbl_product).Include(t=>t.tbl_Addition);
            return View(tbl_order.ToList());
        }

        // GET: order/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            tbl_order tbl_order = db.tbl_order.Find(id);
            if (tbl_order == null)
            {
                return HttpNotFound();
            }
            return View(tbl_order);
        }

        // GET: order/Create
        public ActionResult Create()
        {
            tbl_customerOrder customerOrder = Session["Customer"] as tbl_customerOrder;
            tbl_OrderRequest OrderRequest = Session["Request"] as tbl_OrderRequest;
            tbl_order order = new tbl_order();
            if (OrderRequest != null)
            {
                order.details_order = OrderRequest.description;
            }
            order.fk_customer_id = customerOrder.pk_id_customerOrder;
            ViewBag.Name = customerOrder.name;
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty");
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name");
            ViewBag.fk_id_addition = new SelectList(db.tbl_Addition, "pk_id_addition", "name");
            return View(order);

        }

        // POST: order/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(tbl_order order_table)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        order_table.order_status = "Not Yet";
                        db.tbl_order.Add(order_table);
                        order_table.date = DateTime.Now;
                        tbl_design design = db.tbl_design.Find(order_table.fk_design_id);
                        tbl_product product = db.tbl_product.Find(order_table.fk_product_id);
                        tbl_Addition addition = db.tbl_Addition.Find(order_table.fk_product_id);
                        order_table.price = (order_table.lenght_meter * order_table.width_meter * product.product_price + design.design_price+addition.price) * order_table.amount;
                        db.tbl_order.Add(order_table);
                        db.SaveChanges();

                        tbl_payment total = new tbl_payment();
                        total.fk_id_customerOrder = order_table.fk_customer_id;
                        double? totalprice = db.tbl_order.Where(item => item.fk_customer_id == total.fk_id_customerOrder).Select(item => item.price).DefaultIfEmpty().Sum();
                        total.order_status = "Not Yet";
                        total.total_price = totalprice;
                        total.payment_status = "Not Yet";
                        db.tbl_payment.Add(total);
                        db.SaveChanges();
                        //send EMail
                        var email = db.tbl_customerOrder.Where(item => item.pk_id_customerOrder == total.fk_id_customerOrder).FirstOrDefault();
                        var order = db.tbl_order.Where(item => item.fk_customer_id == email.pk_id_customerOrder);
                        var link = "<a href='" + Request.Url.Scheme + "://" + Request.Url.Authority + @Url.Action("getEmail", "HomeCustomer", new { id = total.pk_id_payment }) + "'>Click here to Pay</a>";

                        string data =
                            "Dear " + email.name + "<br/>" +
                            "Here's Your Details Order <br/>" +
                            "No. Payment : " + total.pk_id_payment +" ("+link+")<br/>" +
                            "Total Price : " + total.total_price + "<br/>" +
                            "===========================================<br/>" +
                            "Your Product : <br/>" +
                            "-----------------------------------------------<br/>";
                        foreach (var item in order)
                        {
                            data +=
                                "Product Name : " + item.tbl_product.product_name + "<br/>" +
                                "Width : " + item.width_meter + " Lenght : " + item.lenght_meter + "<br/>" +
                                "Amount : " + item.amount + "<br/>" +
                                "Details : " + item.details_order + "<br/>" +
                                "-----------------------------------------<br/>";
                        }

                        data +=
                            "How to Pay : <br/>" +
                            "1. Go to Peri.com<br/>" +
                            "2. choose Order, click on Upload Payment<br/>" +
                            "3. Input your no.Payment (Attached on top of this email)<br/>" +
                            "4. Input your payment proof and the rest of data, click on submit button<br/><br/>" +
                            "Please Pay your Order before 24 hour or order will be deleted<br/>" +
                            "===============================================================<br/>";
                        var fromEmail = new MailAddress("periofficial.company@gmail.com", "PERI");
                        var toEmail = new MailAddress(email.email);
                        var fromEmailPassword = "logPeri987"; // Replace with actual password


                        string subject = "";
                        string body = "";
                        subject = "Your Order is Accepted!";
                        body = data;



                        var smtp = new SmtpClient
                        {
                            Host = "smtp.gmail.com",
                            Port = 587,
                            EnableSsl = true,
                            DeliveryMethod = SmtpDeliveryMethod.Network,
                            UseDefaultCredentials = true,
                            Credentials = new NetworkCredential(fromEmail.Address, fromEmailPassword)
                        };

                        using (var msg = new MailMessage(fromEmail, toEmail)
                        {
                            Subject = subject,
                            Body = body,
                            IsBodyHtml = true

                        })
                            smtp.Send(msg);
                        //send Email

                        
                        transaction.Commit();
                
                        return RedirectToAction("Index", "payment");

                    }
                    catch (Exception ex) { transaction.Rollback(); ViewData["Data"] = ex.Message; }
                }

            }
     
  

            ViewBag.fk_customer_id = new SelectList(db.tbl_customerOrder, "pk_id_customerOrder", "name", order_table.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", order_table.fk_design_id);
            ViewBag.fk_product_id = new SelectList(db.tbl_product, "pk_id_product", "product_name", order_table.fk_product_id);
            ViewBag.fk_id_addition = new SelectList(db.tbl_Addition, "pk_id_addition", "name",order_table.fk_id_addition);
            return View(order_table);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AnotherOrder( tbl_order order_table)
        {
            if (ModelState.IsValid)
            {
                using (DbContextTransaction transaction = db.Database.BeginTransaction())
                {
                    try
                    {
                        order_table.date = DateTime.Now;
                        order_table.order_status = "Not Yet";
                        db.tbl_order.Add(order_table);
                        tbl_design design = db.tbl_design.Find(order_table.fk_design_id);
                        tbl_product product = db.tbl_product.Find(order_table.fk_product_id);
                        tbl_Addition addition = db.tbl_Addition.Find(order_table.fk_product_id);
                        order_table.price = (order_table.lenght_meter * order_table.width_meter * product.product_price + design.design_price+addition.price) * order_table.amount;
                        db.tbl_order.Add(order_table);
                        db.SaveChanges();
                        transaction.Commit();
                        return RedirectToAction("Create");
                    }
                    catch (Exception ex)
                    {
                        transaction.Rollback(); ViewData["Data"] = ex.Message;
                    }
                }

            }
            
            //ViewBag.fk_customer_id = new SelectList(db.customers, "pk_id_customer", "name", order_table.fk_customer_id);
            ViewBag.fk_design_id = new SelectList(db.tbl_design, "pk_id_design", "difficulty", order_table.fk_design_id);

PERI_Project/Views/order/Create.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
 
    <div class="container">
        <div class="form-horizontal">
            <h2> @ViewBag.Name</h2>
            <h4>Create Order</h4>

            <hr />
            <div class="form-group">
                <label class="text">Information : <label> Form is required (</label><label style="color:red"> * </label>)</label>
            </div>
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.fk_customer_id)
            @*<div class="form-group">
            @Html.LabelFor(model => model.fk_customer_id, "ID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fk_customer_id, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.fk_customer_id, "", new { @class = "text-danger" })
            </div>
        </div>*@




        <div class="form-group">
            <label class="control-label col-md-2"><b>Length (Meter)<label style="color:red"> *</label></b></label>
            @*@Html.LabelFor(model => model.lenght_meter, "Length (Meter)", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.lenght_meter, new { htmlAttributes = new { @class = "form-control", @onkeyup = "validAngka(this)", required = "required" } })
                @Html.ValidationMessageFor(model => model.lenght_meter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"><b>Width (Meter)<label style="color:red"> *</label></b></label>
            @*@Html.LabelFor(model => model.width_meter, "Width (Meter)", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.EditorFor(model => model.width_meter, new { htmlAttributes = new { @class = "form-control", @onkeyup = "validAngka(this)", required = "required" } })
                @Html.ValidationMessageFor(model => model.width_meter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2"><b>Design Difficulty@*<label style="color:red"> *</label>*@</b></label>
            @*@Html.LabelFor(model => model.fk_design_id, "Design Difficulty", htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
                @Html.DropDownList("fk_design_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_design_id, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                <label class="control-label col-md-2"><b>Product@*<label style="color:red"> *</label>*@</b></label>
                @*@Html.LabelFor(model => model.fk_product_id, "Product", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.DropDownList("fk_product_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.fk_product_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2"><b>Amount<label style="color:red"> *</label></b></label>
                @*@Html.LabelFor(model => model.amount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control", @onkeyup = "validAngka(this)", required = "required" } })
                    @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
                </div>
            </div>

             <div class="form-group">
                 <label class="control-label col-md-2"><b>Addition@*<label style="color:red"> *</label>*@</b></label>
            <div class="col-md-10">
                @Html.DropDownList("fk_id_addition", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.fk_id_addition, "", new { @class = "text-danger" })
            </div>
        </div>

            <div class="form-group">
                <label class="control-label col-md-2"><b>Details Order<label style="color:red"> *</label></b></label>
                @*@Html.LabelFor(model => model.details_order, "Details Order", htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    @*<textarea class="input" name="details_order" id="details_order" style="resize:none; width:871px; height:200px; border-radius:5px;" required></textarea>*@
                    @Html.TextAreaFor(model => model.details_order, 8, 106, new { htmlAttributes = new { @class = "form-control", required = "required", @style = "resize:none;" } })
                    @Html.ValidationMessageFor(model => model.details_order, "", new { @class = "text-danger" })
                </div>
            </div>
            @*<div class="form-group">
            @Html.LabelFor(model => model.price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
            </div>
        </div>*@

            @*<div class="form-group">
            @Html.LabelFor(model => model.date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
            </div>
        </div>*@

            @*<div class="form-group">
            @Html.LabelFor(model => model.order_status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.order_status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.order_status, "", new { @class = "text-danger" })
            </div>
        </div>*@

            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Create" class="btn btn-success" /> |
                    <input type="submit" value="Another Order" formmethod="post" formaction="@Url.Action("AnotherOrder","order")" class="btn btn-primary" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "payment")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script src="~/Scripts_UserLogin/ScriptValidationAngka.js"></script>

PERI_Project/Views/order/Delete.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h3 class="text-success">Are you sure you want to delete this?</h3>
    <div>
        <h4>Delete Order</h4>
        <hr />
        <dl class="dl-horizontal">
          

            <dt>
                Details Order
            </dt>

            <dd>
                @Html.DisplayFor(model => model.details_order)
            </dd>

            <dt>
                Length(meter)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.lenght_meter)
            </dd>

            <dt>
                Width (meter)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.width_meter)
            </dd>

            <dt>
                Amount
                @*@Html.DisplayNameFor(model => model.amount)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.amount)
            </dd>

            <dt>
                Price
                @*@Html.DisplayNameFor(model => model.price)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.price)
            </dd>

            <dt>
                Date
                @*@Html.DisplayNameFor(model => model.date)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>

            <dt>
                Order Status
            </dt>

            <dd>
                @Html.DisplayFor(model => model.order_status)
            </dd>

            <dt>
                Customer Name
                @*@Html.DisplayNameFor(model => model.tbl_customerOrder.name)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_customerOrder.name)
            </dd>

            <dt>
                Difficulty
               @* @Html.DisplayNameFor(model => model.tbl_design.difficulty)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_design.difficulty)
            </dd>

            <dt>
                Product Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_product.product_name)
            </dd>

        </dl>

    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a class="btn btn-info" href="@Url.Action("Index", "payment")">Back to List</a>
        </div>
    </div>
}

PERI_Project/Views/order/Details.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h4>Details Order</h4>
    <hr />
    <dl class="dl-horizontal">
            <dt>
                Design Image
            </dt>
            <dd>
                <img src="@Url.Content(Model.ImagePath)" width="200" height="200" multiple />
            </dd>
            <dt>
                Details Order
            </dt>

            <dd>
                @Html.DisplayFor(model => model.details_order)
            </dd>

            <dt>
                Length(meter)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.lenght_meter)
            </dd>

            <dt>
                Width(meter)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.width_meter)
            </dd>

            <dt>
                Amount
                @*@Html.DisplayNameFor(model => model.amount)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.amount)
            </dd>

            <dt>
                Price
                @*@Html.DisplayNameFor(model => model.price)*@
            </dt>
        
        
            <dd>
                @Html.DisplayFor(model => model.price)
            </dd>

            <dt>
                Date
                @*@Html.DisplayNameFor(model => model.date)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.date)
            </dd>

            <dt>
                Order status
            </dt>

            <dd>
                @Html.DisplayFor(model => model.order_status)
            </dd>

            <dt>
                Customer Name
                @*@Html.DisplayNameFor(model => model.tbl_customerOrder.name)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_customerOrder.name)
            </dd>

            <dt>
                Difficulty
                @*@Html.DisplayNameFor(model => model.tbl_design.difficulty)*@
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_design.difficulty)
            </dd>

            <dt>
                Product Name
            </dt>

            <dd>
                @Html.DisplayFor(model => model.tbl_product.product_name)
            </dd>
        
    </dl>
    <p>
        <a class="btn btn-info" href="@Url.Action("Index", "order")">Back to List</a>
        @*@Html.ActionLink("Back to List", "Index", "payment", new { }, new { })*@
    </p>
</div>

PERI_Project/Views/order/Edit.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@using (Html.BeginForm("Edit", "order", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="form-horizontal">
            <h4>Edit Order</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.pk_id_order)
            @Html.HiddenFor(model => model.fk_customer_id)
            @*<div class="form-group">
                    @Html.LabelFor(model => model.fk_customer_id, "fk_customer_id", htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownList("fk_customer_id", null, htmlAttributes: new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.fk_customer_id, "", new { @class = "text-danger" })
                    </div>
                </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.details_order, "Details Order", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.details_order, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.details_order, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.lenght_meter, "Length (meter)",htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.lenght_meter,  new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.lenght_meter, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.width_meter, "Width (meter)", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.width_meter, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.width_meter, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fk_design_id, "Difficulty", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("fk_design_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.fk_design_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.fk_product_id, "Product", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("fk_product_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.fk_product_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.amount, "Amount", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.amount, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.amount, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.price, "Price", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.price, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.price, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.date, "Date", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.date, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.date, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.order_status, "Order Status", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.order_status, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.order_status, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.ImagePath, "Image Design", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" required>
                </div>
            </div>*@


            <div class="form-group">
                <div class="col-md-10">
                    <input type="submit" value="Save" class="btn btn-secondary" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "order")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PERI_Project/Views/order/Upload.cshtml
@model PERI_Project.Models.tbl_order

@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}




@using (Html.BeginForm("Upload", "order", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container">
        <div class="form-horizontal">
            <h2>Data Order</h2>
            <h4>Upload Design</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.pk_id_order)
            @Html.HiddenFor(model => model.fk_customer_id)
            @Html.HiddenFor(model => model.details_order)
            @Html.HiddenFor(model => model.lenght_meter)
            @Html.HiddenFor(model => model.width_meter)
            @Html.HiddenFor(model => model.fk_design_id)
            @Html.HiddenFor(model => model.fk_product_id)
            @Html.HiddenFor(model => model.amount)
            @Html.HiddenFor(model => model.price)
            @Html.HiddenFor(model => model.date)
            @Html.HiddenFor(model => model.order_status)

            <div class="form-group">
                @Html.LabelFor(model => model.ImagePath, "Upload Design", new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="ImageFile" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-secondary" /> |
                    <a class="btn btn-info" href="@Url.Action("Index", "order")">Back to List</a>
                </div>
            </div>
        </div>
    </div>
}


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}